[project]
name = "crud-jwt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Santhosh-kumar2004", email = "sk2004santhoshkumar@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
crud-jwt = "crud_jwt:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
